# This file was originally generated by PyScripter's unitest wizard

import unittest
import decorator


class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testmakebold(self):
        pass

    def testmakeitalic(self):
        pass

    def testhello(self):
        pass


    def a(self):
        pass


if __name__ == '__main__':
    unittest.main()
