#lang scheme
"====Ex3.1"
(define (make-accumulator init)
  (define acc init)
  (lambda (add)
    (set! acc (+ acc add))
    acc))
(define A (make-accumulator 5))
(A 10)
(A 10)


"====Ex3.2"
(define (make-monitored f)
  (define count 0)
  (define (inc) (set! count (+ count 1)))
  (define (dispatch m)
    (cond ((eq? m 'how-many-calls?) count)
          (else (begin (inc) (f m)))))
  dispatch)

(define s (make-monitored sqrt))
(s 100)
(s 'how-many-calls?)
(s 100)
(s 'how-many-calls?)

"====Ex3.3"
(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount)))
  (define (dispatch pw m)
    (cond ((not (eq? password pw)) (error "Incorrect password for" m))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknow request -- MAKE-ACCOUNT" m))))
  dispatch)
(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
;((acc 'some-other-password 'deposit) 50)


"====Ex3.4"
(define (new-make-account balance password)
  (define err_cnt 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount)))
  (define (inc_errpw)
    (set! err_cnt (+ err_cnt 1))
    err_cnt)
  (define (clear_errpw)
    (set! err_cnt 0))
  (define (call-the-cops useless-arg) 
    (display "call-the-cops\n"))
  (define (display-wrong-password-message useless-arg)                
    (display "Incorrect password\n"))                             
  (define (dispatch pw m)
    (if (eq? password pw)
        (begin (clear_errpw)
               (cond ((eq? m 'withdraw) withdraw)
                     ((eq? m 'deposit) deposit)
                     (else (error "Unknow request -- MAKE-ACCOUNT\n"))))
        (if (>= (inc_errpw) 7) 
            call-the-cops
            display-wrong-password-message)))            
  dispatch)
(define new-acc (new-make-account 100 'secret-password))
((new-acc 'secret-password 'withdraw) 40)
((new-acc 'secret-password1 'withdraw) 40)
((new-acc 'secret-password2 'withdraw) 40)
((new-acc 'secret-password3 'withdraw) 40)
((new-acc 'secret-password4 'withdraw) 40)
((new-acc 'secret-password5 'withdraw) 40)
((new-acc 'secret-password6 'withdraw) 40)
((new-acc 'secret-password7 'withdraw) 40)
((new-acc 'secret-password8 'withdraw) 40)
((new-acc 'secret-password 'withdraw) 40)
((new-acc 'secret-password 'withdraw) 40)
((new-acc 'secret-password8 'withdraw) 40)